### ISSUE TITLE
E10s support

### ISSUE THREAD

**Issue by mirh** [jshackles/Enhanced_Steam_Firefox#104]
Just checked with Add-on Compatibility Reporter and the extension has no explicit support for multiprocess. 
Wouldn't know if there are actual problems or not then. 

https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by mirh** [comment]
Bump?

**Comment by jshackles** [comment]
The newest version of Enhanced Steam was built with Mozilla's WebExtensions API, which is E10 / multiprocess capable.  You can download the newest version directly from the Enhanced Steam website.

**Comment by mirh** [comment]
Thanks!

**Comment by mirh** [comment]
Sorry, another question: why didn't the extension automatically update ?
It [should](https://bugzilla.mozilla.org/show_bug.cgi?id=1214790) be [possible](https://github.com/EFForg/privacybadgerfirefox-legacy/issues/208#issuecomment-250963700) to migrate data and all fiy.

**Comment by jshackles** [comment]
The old version of the extension was hosted on the Mozilla app-store thing, and the new extension is hosted on the Enhanced Steam website.  In order to migrate settings and data, the update would have to come from the Mozilla store and not the site.

Technically, I believe users could manually update their "update source" to point to the JSON update file on Enhanced Steam's website for the older version, but this would still require manual interaction with the code so it would probably be easier and preferable for users to simply download the newest version and go from there.

The version downloaded from the website should remain up-to-date when new releases are pushed out.

**Comment by mirh** [comment]
Oh, interesting. 
Another question now arises though: why ditching mozilla's add-on site?
