### ISSUE TITLE
Enhanced Steam not working on any Steam page.

### ISSUE THREAD

**Issue by stevekh2** [jshackles/Enhanced_Steam_Firefox#107]
Specifically, I was looking at the regional prices for Civilization VI and they are no longer shown. I did a reinstall from the official website, but it was not fixed. Are there any incompatibilities with the latest Firefox (47.0.1)? Thanks.

**Comment by thomas-ashcraft** [comment]
1) Latest Firefox release version is: 49.0.2

2) ES works at steam store pages in latest Firefox version

3) I confirm that ES does not show regional prices (and lowest price also) at store pages. But in short, it caused by WebExtensions API and will be fixed in release branch of Firefox with version 50, which planned release date is November 8, 2016.

**Comment by stevekh2** [comment]
Apparently, you had to force Firefox to update past version 47.0.1 because the newer versions had some bug/crash issues. However, Enhanced Steam is now working fine! Thanks for your help!
