### ISSUE TITLE
Firefox 35 crash

### ISSUE THREAD

**Issue by ahmedtds** [jshackles/Enhanced_Steam_Firefox#60]
After Firefox updated itself to version 35, it started to crash while browsing steam web site. When disabled enhanced steam no crash happens. when enabled it start to crash on steam again.

**Comment by SighmanSays** [comment]
Surely you mean 35, right?

**Comment by ahmedtds** [comment]
yes 35 didn't realized i typed 25 :) thanks for heads up.

**Comment by SighmanSays** [comment]
Np.

Going to dump some info I've ascertained about the problem I've found.

Crashes occur with ES 7.2.2 on Firefox 35.0 and 36.0b1. (I'm using unofficial 64bit builds from [this site](http://xhmikosr.1f0.de/firefox/).) I haven't yet seen it occur with currently 64bit Nightly builds (38.0a1). Does not occur with 34.0 stable.

I think it *may* be linked with login. Every time a crash occurs, I am then logged out from the steam website. The crash also seems to occur most often when opening a login page (either steam main or offsite such as groupees.com). I also have not seen it occur at all when logged out.

Sometimes ES or its settings can be disabled. I have not ascertained any patterns to this behaviour. It does occur in Nightly builds however.

If the crash does not occur immediately, it appears that the browser will remain stable for the duration of its run.

**Comment by jshackles** [comment]
Having the crash occur on the login page (I have not personally experienced this) means that the crash is relegated to a much smaller subset of code.  This is because Enhanced Steam specifically excludes itself from running most of it's functions if it detects that it's running on the login page.  (see [here](https://github.com/jshackles/Enhanced_Steam_Firefox/blob/dev/data/enhancedsteam.js#L5450) )

In my own testing, I've found that Enhanced Steam (along with all of my other extensions) are disabled automatically in Firefox if I choose not to restart the browser directly from the crash report screen.  I believe this is a safeguard in Firefox to prevent a potential crash loop.

I believe the crashing is the result of [Bug 1073882](https://bugzilla.mozilla.org/show_bug.cgi?id=1073882) being fixed in Firefox 35.  The [Firefox 35 for developers](https://developer.mozilla.org/en-US/Firefox/Releases/35) page indicates "XMLHttpRequest.responseURL has been adapted to the latest spec and doesn't include the fragment ('#xyz') of the URL, if relevant".  Enhanced Steam uses the jQuery .load command with these fragments, which appears to be what's causing the crashing in my test environments.  Updating the jQuery library from 1.11.0 to 1.11.2 does not fix the issue.

The two functions that rely on this combination of functionality are [add_app_badge_progress](https://github.com/jshackles/Enhanced_Steam_Firefox/blob/dev/data/enhancedsteam.js#L1638) and [add_wallet_balance_to_header](https://github.com/jshackles/Enhanced_Steam_Firefox/blob/dev/data/enhancedsteam.js#L851) which may need to be either rewritten or removed to resolve the issue with crashing.

**Comment by SighmanSays** [comment]
Still crashing.  Also, disabled ES on my nightly profile and then visited steampowered.com. Crashed.

**Comment by Lunatrius** [comment]
7.2.2 crashes when loading up [this](http://store.steampowered.com/app/282640/) store page.

**Comment by FuglyLookingGuy** [comment]
Any progress on this? I've had to uninstall ES because it crashes FF on almost every Steam page view. I REALLY miss it.

**Comment by SighmanSays** [comment]
The newset versions of Firefox (35.1, 36b3, Nightly, etc) have patched the underlying bug.

**Comment by FuglyLookingGuy** [comment]
Thanks. Just checked and [FF 35.0.1 (release channel)](https://www.mozilla.org/en-US/firefox/35.0.1/releasenotes/) was available and fixed it.
