### ISSUE TITLE
No effect on steamcommunity (beta for Nightly (49.0a1))

### ISSUE THREAD

**Issue by SakhJack** [jshackles/Enhanced_Steam_Firefox#96]
New beta version for Nightly build seems to work fine on store pages.
But doesn't work on any community pages (market, profile, etc)

Just wondering if it's a known issue or not, not complaining.

Not sure how to contribute to solving this as it's not a "single element missing" problem, script doesn't work entirely on https://steamcommunity.com/

**Comment by jshackles** [comment]
This is currently the result of this bug from Mozilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

Steam's CSP settings are preventing elements from loading from the steampowered.com and api.enhancedsteam.com domain, which breaks most of the functionality and interrupts the script.  When the bug is resolved, Enhanced Steam should work correctly on community pages.

The reason it works on store pages is because Valve did not set a CSP on pages served from the steampowered.com domain.

**Comment by SakhJack** [comment]
Can you bump this when it gets resolved by Mozilla?

**Comment by SakhJack** [comment]
Most features of add-on seems to work properly on Nightly build, closing issue

**Comment by thomas-ashcraft** [comment]
I think you should re-open that issue, because we should count on Stable tree users. Not on those few people who using Dev or Nightly builds.

In Stable Firefox (48 right now) there is not only no effect on steamcommunity but even on steam store after checking some settings. I have tried to reinstall add-on and force default settings at add-on's options page, but it still does not work and have no any effect on any steam pages.
